name: Build and deploy
on: ['push']
#  push:
#    tags:
#      - 'v*'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libluajit-5.1-dev
      - name: Checkout
        uses: actions/checkout@latest
      - name: Build
        run: ./build.sh -r
      - name: Create package
        run: cd build && make package_source
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: galse
          prerelease: false
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/*.bz2
          asset_name: template-cpp-sdl-lua.tar.bz2
          asset_content_type: application/x-tar